import { DriveExportFile } from '../types';

/**
 * Uploads a text/html report directly to Google Drive via multipart upload
 */
export async function uploadReportToDrive(
  accessToken: string,
  fileName: string,
  content: string,
  mimeType: string = 'text/html'
): Promise<DriveExportFile> {
  const metadata = {
    name: fileName,
    mimeType: mimeType,
    description: 'Generated by Stock Analysis & Strategy Dashboard'
  };

  const boundary = '-------314159265358979323846';
  const delimiter = `\r\n--${boundary}\r\n`;
  const closeDelimiter = `\r\n--${boundary}--`;

  const multipartRequestBody =
    delimiter +
    'Content-Type: application/json; charset=UTF-8\r\n\r\n' +
    JSON.stringify(metadata) +
    delimiter +
    `Content-Type: ${mimeType}; charset=UTF-8\r\n\r\n` +
    content +
    closeDelimiter;

  const response = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,webViewLink,createdTime,size',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': `multipart/related; boundary=${boundary}`
      },
      body: multipartRequestBody
    }
  );

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Failed to upload to Google Drive: ${errText}`);
  }

  const data = await response.json();
  return {
    id: data.id,
    name: data.name,
    mimeType: data.mimeType,
    webViewLink: data.webViewLink,
    createdTime: data.createdTime || new Date().toISOString(),
    size: data.size
  };
}

/**
 * Uploads a CSV dataset of historical stock & indicator data to Google Drive
 */
export async function uploadCsvToDrive(
  accessToken: string,
  fileName: string,
  csvContent: string
): Promise<DriveExportFile> {
  return uploadReportToDrive(accessToken, fileName, csvContent, 'text/csv');
}

/**
 * Lists files created by this app in Google Drive
 */
export async function listAppDriveFiles(accessToken: string): Promise<DriveExportFile[]> {
  const query = encodeURIComponent(
    "trashed = false and (mimeType = 'text/html' or mimeType = 'text/csv' or mimeType = 'application/json')"
  );
  const url = `https://www.googleapis.com/drive/v3/files?q=${query}&orderBy=createdTime desc&pageSize=15&fields=files(id,name,mimeType,webViewLink,createdTime,size)`;

  const response = await fetch(url, {
    headers: {
      Authorization: `Bearer ${accessToken}`
    }
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Failed to list Google Drive files: ${err}`);
  }

  const data = await response.json();
  return (data.files || []).map((f: any) => ({
    id: f.id,
    name: f.name,
    mimeType: f.mimeType,
    webViewLink: f.webViewLink || `https://drive.google.com/file/d/${f.id}/view`,
    createdTime: f.createdTime,
    size: f.size
  }));
}
